dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T homework1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -attamayte:$BINTRAY_API_KEY "https://api.bintray.com/content/attamayte/otus_cpp/homework1/$TRAVIS_BUILD_NUMBER/homework1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"